### ISSUE TITLE
Feature Request - automaticaly deleting audio file 

### ISSUE THREAD

**Issue by slopez31** [Mossy1022/Smart-Memos#13]
A useful feature would be to integrate only the transcription without including the audio file link and have the ability to automatically delete it. The audio file is not always useful.

### Proposed Solution:

Two checkboxes in the settings that specify the following default configurations:

Delete the audio file after transcription
Include the audio file link
In the recording model window, insert two switches that allow changing the default behavior.

In any case, it's a very promising plugin, great job!

**Comment by Mossy1022** [comment]
Thank you!  This seems simple enough to add pretty easily.  I'll update you soon with a new release 😁

**Comment by Mossy1022** [comment]
I went ahead and added a checkbox for including the audio file.  It will be checked by default to include the audio file.  Simply uncheck it to have it not included and the setting will save whatever you checked last.

I just released version 1.1.5.  Please let me know if that works

**Comment by Mossy1022** [comment]
Ah I'll also add the ability to delete the audio file.  I just have it so the link isn't displayed when transcribing.  I'll also add delete as well.

**Comment by Mossy1022** [comment]
@slopez31 Version 1.1.7 will have the settings you requested.  Please let me know if this works 😁

**Comment by slopez31** [comment]
Sorry I didn't just see your return. 
I'm going to test it and come back to you asap.
Thanx a lot

**Comment by slopez31** [comment]
It works like a charm, thanx a lot it's great. 
Your plugin could replace dragan naturaly speaking for me :)
