### ISSUE TITLE
Add GPT-4o-mini for text generation

### ISSUE THREAD

**Issue by justanotherjurastudent** [Mossy1022/Smart-Memos#14]
Hey,
please add gpt-4o-mini for the text/markdown generation. :)
Thx!

**Comment by Timwj2005** [comment]
I was about to make the same request.

**Comment by Mossy1022** [comment]
Hey guys! Please update to the latest version (1.1.6) and let me know if that works 😁

**Comment by Mossy1022** [comment]
Hey I'm going to close this issue since its been some time.  I'll reopen if you guys find its not there 😁
