### ISSUE TITLE
Request failed, status 429

### ISSUE THREAD

**Issue by diaovidiu** [Mossy1022/Smart-Memos#18]
Hi everyone,

I have used this wonderful plugin for two weeks already, and it was working fine until a few days ago, when it stopped working with the error: Request Failed, Status 429.

I have uninstalled the plug and reinstalled it, but the problem persists. Below is the error.

Is anyone experiencing the same? Help is very welcome
thanks!

![[Extras/audio/recording-1725952269656.wav]]
plugin:smart-memos:2013 file name:  Extras/audio/recording-1725952269656.wav
plugin:smart-memos:2015 full path:  Extras/audio/recording-1725952269656.wav
[Violation] Forced reflow while executing JavaScript took 42ms
plugin:smart-memos:1990 Request failed, status 429
eval @ plugin:smart-memos:1990
Promise.catch (async)
eval @ plugin:smart-memos:1989
Promise.then (async)
eval @ plugin:smart-memos:1977
Promise.then (async)
eval @ plugin:smart-memos:1974
Promise.then (async)
commandGenerateTranscript @ plugin:smart-memos:1969
editorCallback @ plugin:smart-memos:1841
e.mobileOnly.ql.isMobile.e.checkCallback @ app.js:1
BK @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1

**Comment by diaovidiu** [comment]
Is anyone having the same problem? Or do you know a way to fix it? 
Much appreciated your help!

**Comment by Mossy1022** [comment]
Hey @diaovidiu! So sorry for the delay.  An error 429 typically indicates you do not have sufficient funds in your OpenAI account.  I would check that and let me know if that resolves your issue.

**Comment by diaovidiu** [comment]
Hi @Mossy1022 - indeed, the case was something similar. 
I didn't know that even though I had a paid account, I had to have some credit loaded. Did that, and it's working again.
thank you, good job with this plugin.

**Comment by Mossy1022** [comment]
Great, thanks!  I'm getting ready for a move soon and will have much more time to work on updates for these plugins. Let me know if there's more I can assist you with in the future 😁
