### ISSUE TITLE
Can record audio yet not successful to transcribe.

### ISSUE THREAD

**Issue by linguistic76** [Mossy1022/Smart-Memos#5]
I can record audio to a note.

Yet, there seems to be no option for me to transcribe. "smart transcribe" is not available as an option in command pallete.

When I first start up the plugin, there is an option to "smart transcribe" yet clicking on that saves the audio recording the same as if I clicked the stop button.

Any ideas of what I can try to get transcription working?

**Comment by Mossy1022** [comment]
What version are you running? It should be version 1.1.1.  

<img width="1138" alt="Screenshot 2024-07-06 at 5 03 26 PM" src="https://github.com/Mossy1022/Smart-Memos/assets/52715545/40874293-7130-4ab5-a4b1-df0d8b2bad89">

Do you see any notices that appear after you hit smart transcribe after recording a note similar to the screenshot?

**Comment by linguistic76** [comment]
It's working for me now.

Problem was I did not first open a new note. Instead I started a new note by clicking on the "record smart memo" icon.

It works.  It's great!  Thank you for this great app! 

Solved.

**Comment by Mossy1022** [comment]
No no, thank you!  Let me know if you need help with anything else, or if you'd want to see any new features that you notice would be helpful for you. I'll add an enhancement in a newer release to open a new note if one is not yet open to help others who might experience your same issue.  Thanks for letting me know 😁
