### ISSUE TITLE
Issue Handling Audio Recording Error

### ISSUE THREAD

**Issue by mattjparkerr** [Mossy1022/Smart-Memos#6]
![Screenshot 2024-07-07 at 8 02 30 PM](https://github.com/Mossy1022/Smart-Memos/assets/22875097/bff63d54-d02b-43b4-8e13-2a9087950d78)

See errer in screenshot however when attempting to use obsidian throws an error for handling the audio file.. couldnt figure out anything to chang.e

**Comment by Mossy1022** [comment]
@mattjparkerr To confirm the new release has resolved this issue?

**Comment by mattjparkerr** [comment]
Yes resolved thank you!
