### ISSUE TITLE
Failed to handle audio recording

### ISSUE THREAD

**Issue by dobernike** [Mossy1022/Smart-Memos#7]
![image](https://github.com/Mossy1022/Smart-Memos/assets/26094706/7e18916b-9603-4b3b-933a-29520ca15ebf)

iOS 17

I created secret key in ChatGPT
What exactly restriction I need to use in the key for your plugin?

when I tried to record memo, I got the error

**Comment by EmPonders** [comment]
Same issue.
On Ubuntu 22.04

**Comment by Mossy1022** [comment]
Yes! Sorry for iOS it's temporarily not working.  I fixed a bug for finding files that just introduced this one.  I'm working on it and will update you guys soon with a new release.

**Comment by Mossy1022** [comment]
Sorry I'm working on fixing the issue, but it works fine on my iOS so it's hard for me to troubleshoot what the problem is.  I am using iOS 18, though I don't believe this should be an issue.  

Can you guys tell me where you are saving attachments? It should be under the files and links section of settings - Default location for new attachments.

**Comment by Mossy1022** [comment]
@EmPonders @dobernike  I actually believe I resolve the issue.   Can you update to v1.1.4 of Smart Memos? 

In it recordings are saved in your root folder by default.  If you want recordings to be saved in a specific folder, there is now a settings option where you can specify where your recordings will be saved.

**Comment by EmPonders** [comment]
@Mossy1022 solved! And thank you! This tool is fanastic. I really appreciate you building and sharing it. Know that there will be a thousand little moments that I enjoy just a little more because of something you built :)

**Comment by dobernike** [comment]
@Mossy1022 now I got different one: https://github.com/Mossy1022/Smart-Memos/issues/9

**Comment by dobernike** [comment]
Also, as you could see on iOS, the icons is (?), not mic
