### ISSUE TITLE
Trying to record audio: Request failed 429

### ISSUE THREAD

**Issue by dobernike** [Mossy1022/Smart-Memos#9]
![image](https://github.com/user-attachments/assets/524117fd-7297-4a3b-8a5e-645d406537b7)

MacOS and iOS

**Comment by dobernike** [comment]
Also:
I record audio from Mac, going to iOS and got error in the audio (wav)
Could listen it in Mac, not in iOS 

If I record audio from iOS, I can't hear anything in iOS 
But hear it in Mac

**Comment by Mossy1022** [comment]
Got it.  For request failed of 429, that happens on OpenAI's end.  That error code occurs when there have been too many requests within a short period of time, especially when you're using the free version of OpenAI.  That usually lasts around a minute and then you can try again.  I'm going to see what I can do to help this out though.

**Comment by Mossy1022** [comment]
Hmm, yes that is strange.  When you login to openai and check: https://platform.openai.com/usage

Do you see anything unusual?  Possibly hit your rate limit?  You should just need your openapi key, though it could also be the model you are attempting to use.  I would first check with openAI there to see if there's something up.

**Comment by jeremygentles** [comment]
I am seeing similar behavior. Also using paid openai account with plenty of credit available. 
<img width="354" alt="1" src="https://github.com/user-attachments/assets/e95f4bac-8ba8-4bd7-9ed9-3b503b23591d">
<img width="281" alt="2" src="https://github.com/user-attachments/assets/b1cccf47-66ff-4a2a-b754-5ae6e7314eea">
<img width="288" alt="3" src="https://github.com/user-attachments/assets/65e8149c-c36f-4127-9c96-dd5a7385d083">

**Comment by jeremygentles** [comment]
Just a quick update. This seems like it was related to the file size. The audio file was a 563 MB wave file. Recreated a 78.2 MB MP3 file and it worked fine.

**Comment by Mossy1022** [comment]
Interesting. Thanks for the update.  It should be able to take any file size through chunking.  What I can think of is that having enough chunks where the response is received and a new request is made immediately, you might start getting the error.  I'll see if adjusting that will change things.

**Comment by dobernike** [comment]
> Hmm, yes that is strange. When you login to openai and check: https://platform.openai.com/usage
> 
> Do you see anything unusual? Possibly hit your rate limit? You should just need your openapi key, though it could also be the model you are attempting to use. I would first check with openAI there to see if there's something up.

0 usage
